theme: jekyll-theme-cayman
title: "Test global site title"
description: "Piotr Maj Blog"
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "default"
      author: "Piotr Maj"